SchoolTrack2/News/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.NewView.as_view()),
    path('<int:pk>/', views.NewDetail.as_view(), name='detail'),
]

SchoolTrack2/Schedule/urls.py
from django.urls import path
from . import views

app_name = 'schedule'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:schedule_id>/', views.DetailSchedule, name='DetailSchedule'),
]

SchoolTrack2/SchoolTrack2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('News.urls')),
    path('student/', include('Students.urls')),
    path('teachers/', include('Teacher.urls')),
    path('schedule/', include('Schedule.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SchoolTrack2/Schedule/models.py
from django.db import models


class Schedule(models.Model):
    class_of_lesson = models.CharField("Класс", max_length=3)
    start_firts_lesson_monday = models.CharField('(Понедельник) Начало 1 урока', max_length=11)
    end_firts_lesson_monday = models.CharField("Конец урока", max_length=11)
    first_lesson_monday = models.CharField("Урок", max_length=20)
    start_two_lesson_monday = models.CharField('Начало 2 урока', max_length=11)
    end_two_lesson_monday = models.CharField("Конец урока", max_length=11)
    two_lesson_monday = models.CharField("Урок", max_length=20)
    start_free_lesson_monday = models.CharField('Начало 3 урока', max_length=11)
    end_free_lesson_monday = models.CharField("Конец урока", max_length=11)
    free_lesson_monday = models.CharField("Урок", max_length=20)
    start_four_lesson_monday = models.CharField('Начало 4 урока', max_length=11)
    end_four_lesson_monday = models.CharField("Конец урока", max_length=11)
    four_lesson_monday = models.CharField("Урок", max_length=20)
    start_five_lesson_monday = models.CharField('Начало 5 урока', max_length=11)
    end_five_lesson_monday = models.CharField("Конец урока", max_length=11)
    five_lesson_monday = models.CharField("Урок", max_length=20)
    start_six_lesson_monday = models.CharField('Начало 6 урока', max_length=11)
    end_six_lesson_monday = models.CharField('Конец 6 урока', max_length=11)
    six_lesson_monday = models.CharField("Урок", max_length=20)
    start_seven_lesson_monday = models.CharField('Начало 7 урока', max_length=11)
    end_seven_lesson_monday = models.CharField('Конец 7 урока', max_length=11)
    seven_lesson_monday = models.CharField("Урок", max_length=20)
    start_firts_lesson_tuesday = models.CharField('(Вторник) Начало 1 урока', max_length=11)
    end_firts_lesson_tuesday = models.CharField("Конец урока", max_length=11)
    first_lesson_tuesday = models.CharField("Урок", max_length=20)
    start_two_lesson_tuesday = models.CharField('Начало 2 урока', max_length=11)
    end_two_lesson_tuesday = models.CharField("Конец урока", max_length=11)
    two_lesson_tuesday = models.CharField("Урок", max_length=20)
    start_free_lesson_tuesday = models.CharField('Начало 3 урока', max_length=11)
    end_free_lesson_tuesday = models.CharField("Конец урока", max_length=11)
    free_lesson_tuesday = models.CharField("Урок", max_length=20)
    start_four_lesson_tuesday = models.CharField('Начало 4 урока', max_length=11)
    end_four_lesson_tuesday = models.CharField("Конец урока", max_length=11)
    four_lesson_tuesday = models.CharField("Урок", max_length=20)
    start_five_lesson_tuesday = models.CharField('Начало 5 урока', max_length=11)
    end_five_lesson_tuesday = models.CharField("Конец урока", max_length=11)
    five_lesson_tuesday = models.CharField("Урок", max_length=20)
    start_six_lesson_tuesday = models.CharField('Начало 6 урока', max_length=11)
    end_six_lesson_tuesday = models.CharField('Конец 6 урока', max_length=11)
    six_lesson_tuesday = models.CharField("Урок", max_length=20)
    start_seven_lesson_tuesday = models.CharField('Начало 7 урока', max_length=11)
    end_seven_lesson_tuesday = models.CharField('Конец 7 урока', max_length=11)
    seven_lesson_tuesday = models.CharField("Урок", max_length=20)
    start_first_lesson_wednesday = models.CharField('(Среда) Начало 1 урока', max_length=11)
    end_first_lesson_wednesday = models.CharField("Конец урока", max_length=11)
    first_lesson_wednesday = models.CharField("Урок", max_length=20)
    start_two_lesson_wednesday = models.CharField('Начало 2 урока', max_length=11)
    end_two_lesson_wednesday = models.CharField("Конец урока", max_length=11)
    two_lesson_wednesday = models.CharField("Урок", max_length=20)
    start_free_lesson_wednesday = models.CharField('Начало 3 урока', max_length=11)
    end_free_lesson_wednesday = models.CharField("Конец урока", max_length=11)
    free_lesson_wednesday = models.CharField("Урок", max_length=20)
    start_four_lesson_wednesday = models.CharField('Начало 4 урока', max_length=11)
    end_four_lesson_wednesday = models.CharField("Конец урока", max_length=11)
    four_lesson_wednesday = models.CharField("Урок", max_length=20)
    start_five_lesson_wednesday = models.CharField('Начало 5 урока', max_length=11)
    end_five_lesson_wednesday = models.CharField("Конец урока", max_length=11)
    five_lesson_wednesday = models.CharField("Урок", max_length=20)
    start_six_lesson_wednesday = models.CharField('Начало 6 урока', max_length=11)
    end_six_lesson_wednesday = models.CharField('Конец 6 урока', max_length=11)
    six_lesson_wednesday = models.CharField("Урок", max_length=20)
    start_seven_lesson_wednesday = models.CharField('Начало 7 урока', max_length=11)
    end_seven_lesson_wednesday = models.CharField('Конец 7 урока', max_length=11)
    seven_lesson_wednesday = models.CharField("Урок", max_length=20)
    start_first_lesson_thursday = models.CharField('(Четверг) Начало 1 урока', max_length=11)
    end_first_lesson_thursday = models.CharField("Конец урока", max_length=11)
    first_lesson_thursday = models.CharField("Урок", max_length=20)
    start_two_lesson_thursday = models.CharField('Начало 2 урока', max_length=11)
    end_two_lesson_thursday= models.CharField("Конец урока", max_length=11)
    two_lesson_thursday = models.CharField("Урок", max_length=20)
    start_free_lesson_thursday = models.CharField('Начало 3 урока', max_length=11)
    end_free_lesson_thursday = models.CharField("Конец урока", max_length=11)
    free_lesson_thursday = models.CharField("Урок", max_length=20)
    start_four_lesson_thursday = models.CharField('Начало 4 урока', max_length=11)
    end_four_lesson_thursday = models.CharField("Конец урока", max_length=11)
    four_lesson_thursday = models.CharField("Урок", max_length=20)
    start_five_lesson_thursday = models.CharField('Начало 5 урока', max_length=11)
    end_five_lesson_thursday = models.CharField("Конец урока", max_length=11)
    five_lesson_thursday = models.CharField("Урок", max_length=20)
    start_six_lesson_thursday = models.CharField('Начало 6 урока', max_length=11)
    end_six_lesson_thursday = models.CharField('Конец 6 урока', max_length=11)
    six_lesson_thursday = models.CharField("Урок", max_length=20)
    start_seven_lesson_thursday = models.CharField('Начало 7 урока', max_length=11)
    end_seven_lesson_thursday = models.CharField('Конец 7 урока', max_length=11)
    seven_lesson_thursday = models.CharField("Урок", max_length=20)
    start_first_lesson_friday = models.CharField('(Пятница) Начало 1 урока', max_length=11)
    end_first_lesson_friday = models.CharField("Конец урока", max_length=11)
    first_lesson_friday = models.CharField("Урок", max_length=20)
    start_two_lesson_friday = models.CharField('Начало 2 урока', max_length=11)
    end_two_lesson_friday= models.CharField("Конец урока", max_length=11)
    two_lesson_friday = models.CharField("Урок", max_length=20)
    start_free_lesson_friday = models.CharField('Начало 3 урока', max_length=11)
    end_free_lesson_friday = models.CharField("Конец урока", max_length=11)
    free_lesson_friday = models.CharField("Урок", max_length=20)
    start_four_lesson_friday = models.CharField('Начало 4 урока', max_length=11)
    end_four_lesson_friday = models.CharField("Конец урока", max_length=11)
    four_lesson_friday = models.CharField("Урок", max_length=20)
    start_five_lesson_friday = models.CharField('Начало 5 урока', max_length=11)
    end_five_lesson_friday = models.CharField("Конец урока", max_length=11)
    five_lesson_friday = models.CharField("Урок", max_length=20)
    start_six_lesson_friday = models.CharField('Начало 6 урока', max_length=11)
    end_six_lesson_friday = models.CharField('Конец 6 урока', max_length=11)
    six_lesson_friday = models.CharField("Урок", max_length=20)
    start_seven_lesson_friday = models.CharField('Начало 7 урока', max_length=11)
    end_seven_lesson_friday = models.CharField('Конец 7 урока', max_length=11)
    seven_lesson_friday = models.CharField("Урок", max_length=20)
    start_first_lesson_saturday = models.CharField('(Суббота) Начало 1 урока', max_length=11)
    end_first_lesson_saturday= models.CharField("Конец урока", max_length=11)
    first_lesson_saturday = models.CharField("Урок", max_length=20)
    start_two_lesson_saturday = models.CharField('Начало 2 урока', max_length=11)
    end_two_lesson_saturday= models.CharField("Конец урока", max_length=11)
    two_lesson_saturday = models.CharField("Урок", max_length=20)
    start_free_lesson_saturday = models.CharField('Начало 3 урока', max_length=11)
    end_free_lesson_saturday = models.CharField("Конец урока", max_length=11)
    free_lesson_saturday = models.CharField("Урок", max_length=20)
    start_four_lesson_saturday = models.CharField('Начало 4 урока', max_length=11)
    end_four_lesson_saturday = models.CharField("Конец урока", max_length=11)
    four_lesson_saturday = models.CharField("Урок", max_length=20)
    start_five_lesson_saturday = models.CharField('Начало 5 урока', max_length=11)
    end_five_lesson_saturday = models.CharField("Конец урока", max_length=11)
    five_lesson_saturday = models.CharField("Урок", max_length=20)
    start_six_lesson_saturday = models.CharField('Начало 6 урока', max_length=11)
    end_six_lesson_saturday = models.CharField('Конец 6 урока', max_length=11)
    six_lesson_saturday = models.CharField("Урок", max_length=20)
    start_seven_lesson_saturday = models.CharField('Начало 7 урока', max_length=11)
    end_seven_lesson_saturday = models.CharField('Конец 7 урока', max_length=11)
    seven_lesson_saturday = models.CharField("Урок", max_length=20)



    def __str__(self):
        return self.class_of_lesson

    class Meta:
        verbose_name = "Расписание"
        verbose_name_plural = "Расписание"

SchoolTrack2/Schedule/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from .models import Schedule


def index(request):
    klas = Schedule.objects.all()
    return render(request, 'schedule.html', {"klas": klas})


def DetailSchedule(request, schedule_id):
    try:
        a = Schedule.objects.get(id=schedule_id)
    except:
        raise Http404("Такого нет :(")
    return render(request, 'scheduleDetail.html', {'schedule': a})

SchoolTrack2/templates/StudentDetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <style>body{background: linear-gradient(45deg, PaleTurquoise , LightCyan);}</style>
    <div style="background: white; box-shadow: 0.4em 0.4em 5px rgba(122,122,122,0.5); margin-left:300px; margin-right:300px; border-radius: 10px; padding:10px;">
        <div align="center" style="margin-top:100px"><img src="{{ student.photo.url }}" width="300" height="400"></div>
        <div style="font-size:40px;" align="center"><b>{{ student.name }}</b></div>
        <div style="font-size:30px; margin-top:30px;" align="center">{{ student.achivement }}</div>
        <div style="font-size:30px; margin-top:20px;" align="center"><font color="blue">Классный руководитель -</font>  {{ student.teacher_of_class }}</div>
    </div>
{% endblock %}

SchoolTrack2/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
    <head>
            <meta charset="UTF-8">
            <title>Школьный трекер</title>
            <link rel="stylesheet" href="{% static 'css/cssForHeader.css' %}">
            <link rel="shortcut icon" href=" media/ico.png" type="image/png">
    </head>
    <body>
        <nav role='navigation'>
              <ul>
                    <li><a href="/">Главная</a></li>
                    <li><a href="/student">Гонка</a></li>
                    <li><a href="/teachers">Учителя</a></li>
                    <li><a href="/schedule">Расписание</a></li>
                    <li><a href="/admin" style="color:blue;">Вход</a></li>
              </ul>
        </nav>
        {% block content %}{% endblock %}
    </body>
</html>

SchoolTrack2/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <head>
        <style>
                        #glaw{
              margin:auto;
              width:1300px;
            }
            .blok1{
              background:white;
              float:left;
              margin:3px 3px 3px 5px;
              width:300px;
              height:300px;
              padding: 5px;
              text-align: center;
              border-radius: 4px;
              box-shadow: rgba(0,0,0,1.2) 0px 1px 3px;
            }
            .blok1:hover{
                box-shadow:
                        1px 1px #00CED1,
                        2px 2px #00CED1,
                        3px 3px #00CED1,
                        4px 4px #00CED1,
                        5px 5px #00CED1,
                        6px 6px #00CED1,
                        7px 7px #00CED1;
                      -webkit-transform: translateX(-7px);
                      transform: translateX(-7px);
            }
        </style>
        <link rel="stylesheet" href="{% static 'css/listNews.css' %}">
    </head>
    <div class="photobg" style="padding-bottom:50px; padding-top:100px;">
        <p style="margin-top:100px; font-size:100px; margin-left:10px;">Трекер школы №49</p>
        <p style="margin-left:20px;margin-top:30px;font-size:30px;">Узнавай расписание, своё место в рейтинге и самые свежие новости твоей школы!</p>
    </div>
    <div>
        <p style="margin-left:20px;margin-top:30px;font-size:30px;">Новости школы</p>
 <img src="https://cdn-nus-1.pinme.ru/tumb/600/photo/d2/5a/d25a2186f4201ca85545ae4f9a9a8efb.gif" align="right" style="margin-top:-100px">
            {% for new in newlist %}
        <a href="{% url 'detail' new.pk %}">
        <div class="blok1" style="margin:20px; margin-top:30px;" width="50%">
            <p style="color:black; font-size:30px;"><b>{{ new.title }}</b></p>
            <img src="media/znak.png">

        </div>
        </a>
            {% endfor %}
    </div>
        <div class="container">
  <section style="height:80px;"></section>
  <div class="row" style="text-align:center; width:100%;">
  </div>
</div>
{% endblock %}

SchoolTrack2/templates/listStudents.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <head>
            <link rel="stylesheet" href="{% static 'css/listStudents.css' %}">
    </head>
    <style>
        body{
            background: linear-gradient(45deg, PaleTurquoise , LightCyan);
        }
    </style>
    <div style="background:white; margin-left:100px; margin-right:100px; box-shadow: 0.4em 0.4em 5px rgba(122,122,122,0.5); border-radius: 10px; ">
        <div align="center" style="margin-top:100px; font-size:30px">В этом разделе ты можешь посмотреть своё место в рейтинге,</br>а также за что именно были поставленны баллы.</div>
        <div style="margin-top:50px; margin-left:350px; margin-right:100px;">
            <ul class="list3a">
                {% for student in students %}
                    <li><font color="blue">Баллы:{{ student.balls }}</font> - <a href="{% url 'studentdetail' student.id %}" style="color:black">{{ student.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}

SchoolTrack2/templates/listTeacher.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <head>
        <style>
            #glaw{
              width:1100px;
            }
            .blok1{
              background:white;
              float:left;
              margin:3px 3px 3px 5px;
              width:300px;
              height:300px;
              padding: 5px;
              text-align: center;
              border-radius: 4px;
              box-shadow: rgba(0,0,0,1.2) 0px 1px 3px;
            }
        </style>
    </head>
    <div style=" background:white;">
        <style>
            body{
                background: linear-gradient(45deg, PaleTurquoise , LightCyan);
            }
        </style>
    <div style=" background:white;">
        <div id="glaw" style="margin-top:200px; margin:130px; background:white;" align="center">
         {% for teacher in teacher%}
            <div class="blok1">
                <h3>{{ teacher.name }}</h3>
                   <p>{{ teacher.rang }}</p>
                    <img class="alignright size-full wp-image-533"
                    src="{{ teacher.photo.url }}"
                    align="center" width="150" height="200"  style="margin-top:10px"/>

            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

SchoolTrack2/templates/newdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>body{background: linear-gradient(45deg, PaleTurquoise , LightCyan);}</style>
    <div style="background:white; width:1100px; margin-left:100px; margin-right:100px;  box-shadow: 0.4em 0.4em 5px rgba(122,122,122,0.5); border-radius: 10px; padding:10px;"align="center">
            <p style="margin-top:100px; font-size:50px;" align="center"><b>{{ new.title }}</b></p>
            <p align="center"><img src="{{ new.image.url }}" width="700" height="450"></p>
            <p align="center" style="font-size:30px">{{ new.text }}</p>
            <p style="margin-top:20px; opacity:0.7"  align="center">{{ new.date }}</p>
    </div>
{% endblock %}

SchoolTrack2/templates/schedule.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/schedule.css' %}">
</head>
        <style>
            body{
                background: linear-gradient(45deg, PaleTurquoise , LightCyan);
            }
        </style>
            <ul class="list2b" style="margin-top:100px;">
            {% for class in klas %}
                <li><a href="{% url 'schedule:DetailSchedule' class.id %}"><div style="font-size:50px;"><b>{{ class.class_of_lesson }}</b></div></div></a></li>
            {% endfor %}
            </ul>
{% endblock %}

SchoolTrack2/templates/scheduleDetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
</head>
<div style="margin-top:100px;" align="center">
    <table>
        <tr><th colspan="5">Расписание уроков {{ schedule.class_of_lesson }}</th></tr>
             <tr>
                  <td>Понедельник</td>
                  <td>Вторник</td>
                  <td>Среда</td>
                  <td>Четверг</td>
                  <td>Пятница</td>
                    <td>Суббота</td>
             </tr>
            <tr>
                  <td>{{ schedule.first_lesson_monday }}</td>
                  <td>{{ schedule.first_lesson_tuesday }}</td>
                  <td>{{ schedule.first_lesson_wednesday }}</td>
                  <td>{{ schedule.first_lesson_thursday }}</td>
                  <td>{{ schedule.first_lesson_friday }}</td>
                <td>{{ schedule.first_lesson_saturday }}</td>
            </tr>
            <tr>
                  <td>{{ schedule.two_lesson_monday }}</td>
                  <td>{{ schedule.two_lesson_tuesday }}</td>
                  <td>{{ schedule.two_lesson_wednesday }}</td>
                  <td>{{ schedule.two_lesson_thursday }}</td>
                  <td>{{ schedule.two_lesson_friday }}</td>
                <td>{{ schedule.two_lesson_saturday }}</td>
            </tr>
            <tr>
                  <td>{{ schedule.free_lesson_monday }}</td>
                  <td>{{ schedule.free_lesson_tuesday }}</td>
                  <td>{{ schedule.free_lesson_wednesday }}</td>
                  <td>{{ schedule.free_lesson_thursday }}</td>
                  <td>{{ schedule.free_lesson_friday }}</td>
                <td>{{ schedule.free_lesson_saturday }}</td>
            </tr>
            <tr>
                  <td>{{ schedule.four_lesson_monday }}</td>
                  <td>{{ schedule.four_lesson_tuesday }}</td>
                  <td>{{ schedule.four_lesson_wednesday }}</td>
                  <td>{{ schedule.four_lesson_thursday }}</td>
                  <td>{{ schedule.four_lesson_friday }}</td>
                    <td>{{ schedule.four_lesson_saturday }}</td>
            </tr>
          <tr>
              <td>{{ schedule.five_lesson_monday }}</td>
              <td>{{ schedule.five_lesson_tuesday }}</td>
              <td>{{ schedule.five_lesson_wednesday }}</td>
              <td>{{ schedule.five_lesson_thursday }}</td>
              <td>{{ schedule.five_lesson_friday }}</td>
              <td>{{ schedule.five_lesson_saturday }}</td>
          <td colspan="3"></td>
        </tr>
                  <tr>
              <td>{{ schedule.six_lesson_monday }}</td>
              <td>{{ schedule.six_lesson_tuesday }}</td>
              <td>{{ schedule.six_lesson_wednesday }}</td>
              <td>{{ schedule.six_lesson_thursday }}</td>
              <td>{{ schedule.six_lesson_friday }}</td>
              <td>{{ schedule.six_lesson_saturday }}</td>
          <td colspan="3"></td>
        </tr>
        <tr>
              <td>{{ schedule.seven_lesson_monday }}</td>
              <td>{{ schedule.seven_lesson_tuesday }}</td>
              <td>{{ schedule.seven_lesson_wednesday }}</td>
              <td>{{ schedule.seven_lesson_thursday }}</td>
              <td>{{ schedule.seven_lesson_friday }}</td>
              <td>{{ schedule.seven_lesson_saturday }}</td>
          <td colspan="3"></td>
        </tr>

    </table>
</div>
<div style="margin-top:50px;" align="center">
<table >
    <tr><th>Расписание звонков</th>
    <tr><td>1 урок  {{ schedule.start_firts_lesson_monday }} - {{ schedule.end_firts_lesson_monday }}</td></tr>
    <tr><td>2 урок  {{ schedule.start_two_lesson_monday }} - {{ schedule.end_two_lesson_monday }}</td></tr>
    <tr><td>3 урок  {{ schedule.start_free_lesson_monday }} - {{ schedule.end_free_lesson_monday }}</td></tr>
    <tr><td>4 урок  {{ schedule.start_four_lesson_monday }} - {{ schedule.end_four_lesson_monday }}</td></tr>
    <tr><td>5 урок  {{ schedule.start_five_lesson_monday }} - {{ schedule.end_five_lesson_monday }}</td></tr>
    <tr><td>6 урок  {{ schedule.start_six_lesson_monday }} - {{ schedule.end_six_lesson_monday }}</td></tr>
    <tr><td>7 урок  {{ schedule.start_seven_lesson_monday }} - {{ schedule.end_seven_lesson_monday }}</td></tr>
</table>
</div>
{% endblock %}